package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.exception.ApiException;
import com.probestack.forgestudio.design.logging.BusinessOperationEvent;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.Account;
import com.probestack.forgestudio.design.model.CreateAccountRequest;
import com.probestack.forgestudio.design.repository.CreateAccountRequestRepository;
import java.lang.Class;
import java.lang.Exception;
import java.lang.Long;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.System;
import java.lang.reflect.Method;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;
import org.springframework.beans.BeanUtils;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for CreateAccountRequest operations.
 *
 * <p>This service uses MongoDB repository for data persistence.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class AccountsService {
    private final CreateAccountRequestRepository createAccountRequestRepository;

    private final BusinessOperationLogger businessOperationLogger;

    public AccountsService(CreateAccountRequestRepository createAccountRequestRepository,
            BusinessOperationLogger businessOperationLogger) {
        this.createAccountRequestRepository = createAccountRequestRepository;
        this.businessOperationLogger = businessOperationLogger;
    }

    public ResponseEntity<Account> createAccount(CreateAccountRequest createAccountRequest) {
        long businessStartedAt = System.nanoTime();
        try {
            // Save the entity to database
            ensureEntityId(createAccountRequest);
            CreateAccountRequest savedCreateAccountRequest = createAccountRequestRepository.save(createAccountRequest);
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("createAccount")
                            .resource("CreateAccountRequest")
                            .action("CREATE")
                            .status("SUCCESS")
                            .repository("CreateAccountRequestRepository")
                            .collection("erp_services_api_accounts")
                            .documentId(getEntityId(savedCreateAccountRequest))
                            .recordCount(1)
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Map entity to response DTO
            Account response = mapToAccount(savedCreateAccountRequest);
            return ResponseEntity.status(HttpStatus.CREATED).body(response);
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("createAccount")
                            .resource("CreateAccountRequest")
                            .action("CREATE")
                            .status("FAILED")
                            .repository("CreateAccountRequestRepository")
                            .collection("erp_services_api_accounts")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_write_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<Account> getAccount(String accountId) {
        long businessStartedAt = System.nanoTime();
        try {
            // Retrieve entity by ID from database
            String repositoryId = toRepositoryId(accountId);
            Optional<CreateAccountRequest> entity = createAccountRequestRepository.findById(repositoryId);
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getAccount")
                            .resource("CreateAccountRequest")
                            .action("READ")
                            .status("SUCCESS")
                            .repository("CreateAccountRequestRepository")
                            .collection("erp_services_api_accounts")
                            .documentId(repositoryId)
                            .recordCount(entity.isPresent() ? 1 : 0)
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Map entity to response DTO
            return entity.map(this::mapToAccount).map(ResponseEntity::ok).orElseThrow(() -> ApiException.notFound("CreateAccountRequest", repositoryId));
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getAccount")
                            .resource("CreateAccountRequest")
                            .action("READ")
                            .status("FAILED")
                            .repository("CreateAccountRequestRepository")
                            .collection("erp_services_api_accounts")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_read_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<List<Account>> listAccounts() {
        long businessStartedAt = System.nanoTime();
        try {
            // Retrieve all entities from database
            List<CreateAccountRequest> entities = createAccountRequestRepository.findAll();
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("listAccounts")
                            .resource("CreateAccountRequest")
                            .action("READ")
                            .status("SUCCESS")
                            .repository("CreateAccountRequestRepository")
                            .collection("erp_services_api_accounts")
                            .recordCount(entities.size())
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Map entities to response DTOs
            List<Account> responses = entities.stream().map(this::mapToAccount).collect(Collectors.toList());
            return ResponseEntity.ok(responses);
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("listAccounts")
                            .resource("CreateAccountRequest")
                            .action("READ")
                            .status("FAILED")
                            .repository("CreateAccountRequestRepository")
                            .collection("erp_services_api_accounts")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_read_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private String toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        return id.toString();
    }

    /**
     * Assigns a Mongo document ID when the generated model does not have one yet.
     */
    private void ensureEntityId(Object entity) {
        if (entity == null) {
            return;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object currentId = getter.invoke(entity);
            if (currentId == null || currentId.toString().isBlank()) {
                setEntityId(entity, UUID.randomUUID().toString());
            }
        } catch (Exception ignored) {
            // Generated models are enhanced with getId/setId; ignore if custom code removed them.
        }
    }

    private void setEntityId(Object entity, String id) {
        if (entity == null || id == null) {
            return;
        }
        try {
            Method setter = entity.getClass().getMethod("setId", String.class);
            setter.invoke(entity, id);
        } catch (Exception ignored) {
            // Generated models are enhanced with setId; ignore if custom code removed it.
        }
    }

    private String getEntityId(Object entity) {
        if (entity == null) {
            return null;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object value = getter.invoke(entity);
            return value != null ? value.toString() : null;
        } catch (Exception ignored) {
            return null;
        }
    }

    private void copyGeneratedId(Object entity, Object response) {
        String id = getEntityId(entity);
        if (id == null || response == null) {
            return;
        }
        for (Method method : response.getClass().getMethods()) {
            if (method.getName().startsWith("set") && method.getName().endsWith("Id") && method.getParameterCount() == 1 && method.getParameterTypes()[0].equals(String.class)) {
                try {
                    method.invoke(response, id);
                    return;
                } catch (Exception ignored) {
                    // Try the next compatible ID setter.
                }
            }
        }
    }

    /**
     * Creates an empty response wrapper for list/search endpoints.
     */
    private <T> T emptyResponse(Class<T> responseType) {
        try {
            T response = responseType.getDeclaredConstructor().newInstance();
            for (Method method : responseType.getMethods()) {
                if (method.getName().startsWith("set") && method.getParameterCount() == 1 && List.class.isAssignableFrom(method.getParameterTypes()[0])) {
                    method.invoke(response, Collections.emptyList());
                }
            }
            return response;
        } catch (Exception ignored) {
            return null;
        }
    }

    /**
     * Calculates elapsed milliseconds for generated business operation logs.
     */
    private Long businessDurationMs(long startedAt) {
        return (System.nanoTime() - startedAt) / 1_000_000L;
    }

    /**
     * Maps CreateAccountRequest entity to Account response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private Account mapToAccount(CreateAccountRequest entity) {
        // Create new response object
        Account response = new Account();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
