package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.logging.BusinessOperationEvent;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.BalanceSheet;
import com.probestack.forgestudio.design.repository.BalanceSheetRepository;
import java.lang.Class;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.System;
import java.lang.reflect.Method;
import java.util.Collections;
import java.util.List;
import java.util.UUID;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for BalanceSheet operations.
 *
 * <p>This service uses MongoDB repository for data persistence.</p>
 *
 * @author Generated by ProbeStack CodeGen
 */
@Service
public class ReportsService {
    private final BalanceSheetRepository balanceSheetRepository;

    private final BusinessOperationLogger businessOperationLogger;

    public ReportsService(BalanceSheetRepository balanceSheetRepository,
            BusinessOperationLogger businessOperationLogger) {
        this.balanceSheetRepository = balanceSheetRepository;
        this.businessOperationLogger = businessOperationLogger;
    }

    public ResponseEntity<BalanceSheet> getBalanceSheet(Integer fiscalYear) {
        long businessStartedAt = System.nanoTime();
        try {
            // Retrieve all entities from database
            List<BalanceSheet> entities = balanceSheetRepository.findAll();
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getBalanceSheet")
                            .resource("BalanceSheet")
                            .action("READ")
                            .status("SUCCESS")
                            .repository("BalanceSheetRepository")
                            .collection("erp_services_api_reports")
                            .recordCount(entities.size())
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            return ResponseEntity.ok(entities.isEmpty() ? emptyResponse(BalanceSheet.class) : entities.get(0));
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getBalanceSheet")
                            .resource("BalanceSheet")
                            .action("READ")
                            .status("FAILED")
                            .repository("BalanceSheetRepository")
                            .collection("erp_services_api_reports")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_read_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private String toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        return id.toString();
    }

    /**
     * Assigns a Mongo document ID when the generated model does not have one yet.
     */
    private void ensureEntityId(Object entity) {
        if (entity == null) {
            return;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object currentId = getter.invoke(entity);
            if (currentId == null || currentId.toString().isBlank()) {
                setEntityId(entity, UUID.randomUUID().toString());
            }
        } catch (Exception ignored) {
            // Generated models are enhanced with getId/setId; ignore if custom code removed them.
        }
    }

    private void setEntityId(Object entity, String id) {
        if (entity == null || id == null) {
            return;
        }
        try {
            Method setter = entity.getClass().getMethod("setId", String.class);
            setter.invoke(entity, id);
        } catch (Exception ignored) {
            // Generated models are enhanced with setId; ignore if custom code removed it.
        }
    }

    private String getEntityId(Object entity) {
        if (entity == null) {
            return null;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object value = getter.invoke(entity);
            return value != null ? value.toString() : null;
        } catch (Exception ignored) {
            return null;
        }
    }

    private void copyGeneratedId(Object entity, Object response) {
        String id = getEntityId(entity);
        if (id == null || response == null) {
            return;
        }
        for (Method method : response.getClass().getMethods()) {
            if (method.getName().startsWith("set") && method.getName().endsWith("Id") && method.getParameterCount() == 1 && method.getParameterTypes()[0].equals(String.class)) {
                try {
                    method.invoke(response, id);
                    return;
                } catch (Exception ignored) {
                    // Try the next compatible ID setter.
                }
            }
        }
    }

    /**
     * Creates an empty response wrapper for list/search endpoints.
     */
    private <T> T emptyResponse(Class<T> responseType) {
        try {
            T response = responseType.getDeclaredConstructor().newInstance();
            for (Method method : responseType.getMethods()) {
                if (method.getName().startsWith("set") && method.getParameterCount() == 1 && List.class.isAssignableFrom(method.getParameterTypes()[0])) {
                    method.invoke(response, Collections.emptyList());
                }
            }
            return response;
        } catch (Exception ignored) {
            return null;
        }
    }

    /**
     * Calculates elapsed milliseconds for generated business operation logs.
     */
    private Long businessDurationMs(long startedAt) {
        return (System.nanoTime() - startedAt) / 1_000_000L;
    }
}
