package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.model.CreateTransactionRequest;
import com.probestack.forgestudio.design.model.Transaction;
import com.probestack.forgestudio.design.repository.CreateTransactionRequestRepository;
import java.lang.Exception;
import java.lang.Object;
import java.lang.String;
import java.lang.reflect.Method;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;
import org.springframework.beans.BeanUtils;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for CreateTransactionRequest operations.
 *
 * <p>This service uses MongoDB repository for data persistence.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class TransactionsService {
    private final CreateTransactionRequestRepository createTransactionRequestRepository;

    public TransactionsService(
            CreateTransactionRequestRepository createTransactionRequestRepository) {
        this.createTransactionRequestRepository = createTransactionRequestRepository;
    }

    public ResponseEntity<Transaction> createTransaction(
            CreateTransactionRequest createTransactionRequest) {
        // Save the entity to database
        ensureEntityId(createTransactionRequest);
        CreateTransactionRequest savedCreateTransactionRequest = createTransactionRequestRepository.save(createTransactionRequest);
        // Map entity to response DTO
        Transaction response = mapToTransaction(savedCreateTransactionRequest);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    public ResponseEntity<List<Transaction>> listTransactions(String accountId, LocalDate startDate,
            LocalDate endDate) {
        // Retrieve all entities from database
        List<CreateTransactionRequest> entities = createTransactionRequestRepository.findAll();
        // Map entities to response DTOs
        List<Transaction> responses = entities.stream().map(this::mapToTransaction).collect(Collectors.toList());
        return ResponseEntity.ok(responses);
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private String toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        return id.toString();
    }

    /**
     * Assigns a Mongo document ID when the generated model does not have one yet.
     */
    private void ensureEntityId(Object entity) {
        if (entity == null) {
            return;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object currentId = getter.invoke(entity);
            if (currentId == null || currentId.toString().isBlank()) {
                setEntityId(entity, UUID.randomUUID().toString());
            }
        } catch (Exception ignored) {
            // Generated models are enhanced with getId/setId; ignore if custom code removed them.
        }
    }

    private void setEntityId(Object entity, String id) {
        if (entity == null || id == null) {
            return;
        }
        try {
            Method setter = entity.getClass().getMethod("setId", String.class);
            setter.invoke(entity, id);
        } catch (Exception ignored) {
            // Generated models are enhanced with setId; ignore if custom code removed it.
        }
    }

    private String getEntityId(Object entity) {
        if (entity == null) {
            return null;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object value = getter.invoke(entity);
            return value != null ? value.toString() : null;
        } catch (Exception ignored) {
            return null;
        }
    }

    private void copyGeneratedId(Object entity, Object response) {
        String id = getEntityId(entity);
        if (id == null || response == null) {
            return;
        }
        for (Method method : response.getClass().getMethods()) {
            if (method.getName().startsWith("set") && method.getName().endsWith("Id") && method.getParameterCount() == 1 && method.getParameterTypes()[0].equals(String.class)) {
                try {
                    method.invoke(response, id);
                    return;
                } catch (Exception ignored) {
                    // Try the next compatible ID setter.
                }
            }
        }
    }

    /**
     * Maps CreateTransactionRequest entity to Transaction response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private Transaction mapToTransaction(CreateTransactionRequest entity) {
        // Create new response object
        Transaction response = new Transaction();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
